"use server";

import { revalidatePath } from "next/cache";

import { getWorkspaceContext } from "@/lib/supabase/workspace";

export type SalesDocumentActionResult = { ok: boolean; message: string; documentId?: string; field?: string };

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const CODE = /^[A-Za-z0-9/_-]+$/;
const DATE = /^\d{4}-\d{2}-\d{2}$/;
type OrderLine = { item_id: string; ordered_quantity: string; unit_price: string; tax_rate: string };
type FulfillmentLine = { sales_order_line_id: string; item_id: string; quantity: string };

function value(formData: FormData, key: string) { const input = formData.get(key); return typeof input === "string" ? input.trim() : ""; }
function validDate(input: string, label: string) { if (!DATE.test(input)) return `${label} must be a valid date.`; const date = new Date(`${input}T00:00:00.000Z`); return Number.isNaN(date.getTime()) || date.toISOString().slice(0, 10) !== input ? `${label} must be a valid date.` : null; }
function decimal(input: string, label: string, scale: number, allowZero: boolean) { const pattern = new RegExp(`^\\d+(?:\\.\\d{1,${scale}})?$`); if (!input || !pattern.test(input)) return `${label} must be a valid number with up to ${scale} decimal places.`; if (input.split(".")[0].replace(/^0+/, "").length > 15) return `${label} is too large.`; const numberValue = Number(input); if (!Number.isFinite(numberValue) || (!allowZero && numberValue <= 0)) return `${label} must be ${allowZero ? "zero or greater" : "greater than zero"}.`; return null; }
function parseLines<T>(input: string, emptyMessage: string, parse: (line: Record<string, unknown>) => { value?: T; error?: string }, keyOf: (line: T) => string) { if (!input) return { error: emptyMessage }; let parsed: unknown; try { parsed = JSON.parse(input); } catch { return { error: "Document lines are invalid." }; } if (!Array.isArray(parsed) || parsed.length === 0) return { error: emptyMessage }; if (parsed.length > 200) return { error: "A document cannot contain more than 200 lines." }; const lines: T[] = []; const keys = new Set<string>(); for (const raw of parsed) { if (!raw || typeof raw !== "object") return { error: "Document lines are invalid." }; const result = parse(raw as Record<string, unknown>); if (result.error || !result.value) return { error: result.error || "Document lines are invalid." }; const key = keyOf(result.value); if (keys.has(key)) return { error: "An item can appear only once per document." }; keys.add(key); lines.push(result.value); } return { lines }; }
function contextError(status: "unauthenticated" | "needs_onboarding" | "error"): SalesDocumentActionResult { return { ok: false, message: status === "unauthenticated" ? "Your session has expired. Please sign in again." : "Create a workspace before managing sales." }; }
async function permission(context: Awaited<ReturnType<typeof getWorkspaceContext>>, permissionKey: string) { if (context.status !== "ready") return false; const { data, error } = await context.supabase.rpc("has_permission", { required_permission: permissionKey }); return !error && data === true; }
function saveError(error: { code?: string; message?: string }, kind: "order" | "fulfillment"): SalesDocumentActionResult { if (error.code === "23505") return { ok: false, message: "That document number already exists." }; const message = error.message || ""; if (message.includes("Not authorized")) return { ok: false, message: `You do not have permission to create this ${kind}.` }; if (message.includes("Customer")) return { ok: false, message: "Select an active customer from this workspace.", field: "customer_id" }; if (message.includes("Warehouse")) return { ok: false, message: "Select an active warehouse from this workspace.", field: "warehouse_id" }; if (message.includes("reserved")) return { ok: false, message: "The selected warehouse does not have enough reserved stock for these lines. Choose another warehouse or receive stock first.", field: "lines" }; if (message.includes("draft fulfillment")) return { ok: false, message: "A draft fulfillment already exists for this sales order." }; if (message.includes("different")) return { ok: false, message: "Source and destination must be different." }; if (message.includes("exceed") || message.includes("line")) return { ok: false, message: "One or more lines are invalid or exceed the remaining quantity.", field: "lines" }; return { ok: false, message: `Unable to save ${kind}.` }; }
function processError(error: { message?: string }, kind: "order" | "fulfillment"): SalesDocumentActionResult { const message = error.message || ""; if (message.includes("Not authorized")) return { ok: false, message: `You do not have permission to process this ${kind}.` }; if (message.includes("not found")) return { ok: false, message: `This ${kind} no longer exists.` }; if (message.includes("Only draft")) return { ok: false, message: `This ${kind} is already processed. Refresh the page.` }; if (message.includes("Insufficient stock")) return { ok: false, message: "There is not enough stock in the selected warehouse. Refresh stock and try again." }; if (message.includes("exceed")) return { ok: false, message: "The quantity exceeds the remaining quantity. Refresh and try again." }; if (message.includes("no longer active")) return { ok: false, message: "A customer, item, or warehouse is no longer active." }; return { ok: false, message: `Unable to process ${kind}.` }; }

export async function createSalesOrder(formData: FormData): Promise<SalesDocumentActionResult> {
  const customerId = value(formData, "customer_id"); const orderNumber = value(formData, "order_number").toUpperCase(); const orderDate = value(formData, "order_date"); const notes = value(formData, "notes");
  const parsed = parseLines<OrderLine>(value(formData, "lines"), "Add at least one item.", (line) => { const itemId = typeof line.item_id === "string" ? line.item_id.trim() : ""; const quantity = typeof line.ordered_quantity === "string" ? line.ordered_quantity.trim() : ""; const price = typeof line.unit_price === "string" ? line.unit_price.trim() : ""; const tax = typeof line.tax_rate === "string" ? line.tax_rate.trim() : ""; if (!UUID.test(itemId)) return { error: "Select a valid item." }; const lineError = decimal(quantity, "Quantity", 3, false) || decimal(price, "Rate", 2, true) || decimal(tax, "Tax rate", 2, true) || (Number(tax) > 100 ? "Tax rate must be 100 or less." : null); return lineError ? { error: lineError } : { value: { item_id: itemId, ordered_quantity: quantity, unit_price: price, tax_rate: tax } }; }, (line) => line.item_id);
  if (!UUID.test(customerId)) return { ok: false, message: "Select a valid customer.", field: "customer_id" }; if (!orderNumber || orderNumber.length > 40 || !CODE.test(orderNumber)) return { ok: false, message: "Sales order number must use up to 40 letters, numbers, slashes, underscores, or hyphens.", field: "order_number" }; const dateError = validDate(orderDate, "Sales order date"); if (dateError) return { ok: false, message: dateError, field: "order_date" }; if (notes.length > 1000) return { ok: false, message: "Notes must be 1000 characters or fewer.", field: "notes" }; if (parsed.error || !parsed.lines) return { ok: false, message: parsed.error || "Add at least one item.", field: "lines" };
  const context = await getWorkspaceContext(); if (context.status !== "ready") return contextError(context.status); if (!(await permission(context, "sales.create"))) return { ok: false, message: "You do not have permission to create sales orders." };
  const { data, error } = await context.supabase.rpc("create_sales_order", { customer_id: customerId, order_number: orderNumber, order_date: orderDate, notes: notes || null, lines: parsed.lines }); if (error || !data) return saveError(error || { message: "Missing order ID" }, "order"); revalidatePath("/sales-orders"); revalidatePath(`/sales-orders/${data}`); return { ok: true, message: "Sales order saved as draft.", documentId: data };
}

export async function createSalesFulfillment(formData: FormData): Promise<SalesDocumentActionResult> {
  const salesOrderId = value(formData, "sales_order_id"); const warehouseId = value(formData, "warehouse_id"); const fulfillmentNumber = value(formData, "fulfillment_number").toUpperCase(); const fulfillmentDate = value(formData, "fulfillment_date"); const notes = value(formData, "notes");
  const parsed = parseLines<FulfillmentLine>(value(formData, "lines"), "Select at least one item to fulfill.", (line) => { const orderLineId = typeof line.sales_order_line_id === "string" ? line.sales_order_line_id.trim() : ""; const itemId = typeof line.item_id === "string" ? line.item_id.trim() : ""; const quantity = typeof line.quantity === "string" ? line.quantity.trim() : ""; if (!UUID.test(orderLineId) || !UUID.test(itemId)) return { error: "Fulfillment item is invalid." }; const error = decimal(quantity, "Quantity", 3, false); return error ? { error } : { value: { sales_order_line_id: orderLineId, item_id: itemId, quantity } }; }, (line) => line.sales_order_line_id);
  if (!UUID.test(salesOrderId)) return { ok: false, message: "This sales order is invalid." }; if (!UUID.test(warehouseId)) return { ok: false, message: "Select a valid warehouse.", field: "warehouse_id" }; if (!fulfillmentNumber || fulfillmentNumber.length > 40 || !CODE.test(fulfillmentNumber)) return { ok: false, message: "Fulfillment number must use up to 40 letters, numbers, slashes, underscores, or hyphens.", field: "fulfillment_number" }; const dateError = validDate(fulfillmentDate, "Fulfillment date"); if (dateError) return { ok: false, message: dateError, field: "fulfillment_date" }; if (notes.length > 1000) return { ok: false, message: "Notes must be 1000 characters or fewer.", field: "notes" }; if (parsed.error || !parsed.lines) return { ok: false, message: parsed.error || "Select at least one item to fulfill.", field: "lines" };
  const context = await getWorkspaceContext(); if (context.status !== "ready") return contextError(context.status); if (!(await permission(context, "sales.create"))) return { ok: false, message: "You do not have permission to create fulfillments." }; const { data, error } = await context.supabase.rpc("create_sales_fulfillment", { sales_order_id: salesOrderId, warehouse_id: warehouseId, fulfillment_number: fulfillmentNumber, fulfillment_date: fulfillmentDate, notes: notes || null, lines: parsed.lines }); if (error || !data) return saveError(error || { message: "Missing fulfillment ID" }, "fulfillment"); revalidatePath("/sales-orders"); revalidatePath(`/sales-orders/${salesOrderId}`); revalidatePath("/sales-fulfillments"); revalidatePath(`/sales-fulfillments/${data}`); return { ok: true, message: "Fulfillment saved as draft.", documentId: data };
}

export async function submitSalesOrder(id: string): Promise<SalesDocumentActionResult> { return processSalesDocument(id, "submit_sales_order", "sales.edit", "order", "/sales-orders"); }
export async function cancelSalesOrder(id: string): Promise<SalesDocumentActionResult> { return cancelSalesDocument(id, "cancel_sales_order", "sales.edit", "order", "/sales-orders"); }
export async function postSalesFulfillment(id: string): Promise<SalesDocumentActionResult> { return processSalesDocument(id, "post_sales_fulfillment", "sales.post", "fulfillment", "/sales-fulfillments"); }
export async function cancelSalesFulfillment(id: string): Promise<SalesDocumentActionResult> { return cancelSalesDocument(id, "cancel_sales_fulfillment", "sales.edit", "fulfillment", "/sales-fulfillments"); }

async function processSalesDocument(id: string, functionName: string, permissionKey: string, kind: "order" | "fulfillment", path: string) { if (!UUID.test(id)) return { ok: false, message: `This ${kind} ID is invalid.` }; const context = await getWorkspaceContext(); if (context.status !== "ready") return contextError(context.status); if (!(await permission(context, permissionKey))) return { ok: false, message: `You do not have permission to process this ${kind}.` }; const { data, error } = await context.supabase.rpc(functionName, kind === "order" ? { order_id: id } : { fulfillment_id: id }); if (error || (kind === "order" && !data)) return processError(error || { message: `Missing ${kind} ID` }, kind); revalidatePath(path); revalidatePath(`${path}/${id}`); if (kind === "fulfillment") { revalidatePath("/sales-orders"); revalidatePath("/inventory"); revalidatePath("/stock-movements"); revalidatePath("/protected"); } return { ok: true, message: kind === "order" ? "Sales order submitted." : "Fulfillment posted and stock updated.", documentId: id }; }
async function cancelSalesDocument(id: string, functionName: string, permissionKey: string, kind: "order" | "fulfillment", path: string) { if (!UUID.test(id)) return { ok: false, message: `This ${kind} ID is invalid.` }; const context = await getWorkspaceContext(); if (context.status !== "ready") return contextError(context.status); if (!(await permission(context, permissionKey))) return { ok: false, message: `You do not have permission to cancel this ${kind}.` }; const { error } = await context.supabase.rpc(functionName, kind === "order" ? { order_id: id } : { fulfillment_id: id }); if (error) return processError(error, kind); revalidatePath(path); revalidatePath(`${path}/${id}`); return { ok: true, message: `${kind === "order" ? "Sales order" : "Fulfillment"} cancelled.`, documentId: id }; }
