"use server";

import { revalidatePath } from "next/cache";

import { getWorkspaceContext } from "@/lib/supabase/workspace";

export type SalesReturnActionResult = { ok: boolean; message: string; documentId?: string; field?: string };
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const CODE = /^[A-Za-z0-9/_-]+$/;
const DATE = /^\d{4}-\d{2}-\d{2}$/;

function value(formData: FormData, key: string) { const input = formData.get(key); return typeof input === "string" ? input.trim() : ""; }
function validDate(input: string, label: string) { if (!DATE.test(input)) return `${label} must be a valid date.`; const parsed = new Date(`${input}T00:00:00.000Z`); return Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0, 10) !== input ? `${label} must be a valid date.` : null; }
function decimal(input: string, label: string, scale: number, allowZero: boolean) { const pattern = new RegExp(`^\\d+(?:\\.\\d{1,${scale}})?$`); if (!input || !pattern.test(input)) return `${label} must be a valid number with up to ${scale} decimal places.`; if (input.split(".")[0].replace(/^0+/, "").length > 15) return `${label} is too large.`; const parsed = Number(input); if (!Number.isFinite(parsed) || (!allowZero && parsed <= 0)) return `${label} must be ${allowZero ? "zero or greater" : "greater than zero"}.`; return null; }
function parseLines(input: string) { if (!input) return { error: "Select at least one item to return." }; let parsed: unknown; try { parsed = JSON.parse(input); } catch { return { error: "Return lines are invalid." }; } if (!Array.isArray(parsed) || parsed.length === 0 || parsed.length > 200) return { error: "Select between 1 and 200 return lines." }; const lines: Array<{ invoice_line_id: string; quantity: string }> = []; const keys = new Set<string>(); for (const raw of parsed) { if (!raw || typeof raw !== "object") return { error: "Return lines are invalid." }; const line = raw as Record<string, unknown>; const invoiceLineId = typeof line.invoice_line_id === "string" ? line.invoice_line_id.trim() : ""; const quantity = typeof line.quantity === "string" ? line.quantity.trim() : ""; if (!UUID.test(invoiceLineId)) return { error: "A return item is invalid." }; const quantityError = decimal(quantity, "Return quantity", 3, false); if (quantityError) return { error: quantityError }; if (keys.has(invoiceLineId)) return { error: "An invoice line can appear only once per return." }; keys.add(invoiceLineId); lines.push({ invoice_line_id: invoiceLineId, quantity }); } return { lines }; }
function contextError(status: "unauthenticated" | "needs_onboarding" | "error"): SalesReturnActionResult { return { ok: false, message: status === "unauthenticated" ? "Your session has expired. Please sign in again." : "Create a workspace before managing returns." }; }
async function permission(context: Awaited<ReturnType<typeof getWorkspaceContext>>, key: string) { if (context.status !== "ready") return false; const { data, error } = await context.supabase.rpc("has_permission", { required_permission: key }); return !error && data === true; }
function processError(error: { message?: string }, action: "create" | "post" | "cancel"): SalesReturnActionResult { const message = error.message || ""; if (message.includes("Not authorized")) return { ok: false, message: `You do not have permission to ${action} sales returns.` }; if (message.includes("already exists")) return { ok: false, message: "That return number already exists." }; if (message.includes("remaining sold quantity") || message.includes("no longer available")) return { ok: false, message: "One or more quantities are no longer available. Refresh and try again." }; if (message.includes("Refund amount exceeds") || message.includes("Refund amount cannot")) return { ok: false, message: message.includes("refundable") ? "The refund exceeds the customer’s refundable paid balance." : "The refund cannot exceed the returned items total." }; if (message.includes("Only issued")) return { ok: false, message: "Only an issued invoice can be returned." }; if (message.includes("Only draft")) return { ok: false, message: `This return is already ${action === "post" ? "processed" : "closed"}. Refresh the page.` }; if (message.includes("warehouse")) return { ok: false, message: "The original warehouse is no longer active." }; return { ok: false, message: `Unable to ${action} sales return. Refresh and try again.` }; }

export async function createSalesReturn(formData: FormData): Promise<SalesReturnActionResult> {
  const invoiceId = value(formData, "invoice_id"); const returnNumber = value(formData, "return_number").toUpperCase(); const returnDate = value(formData, "return_date"); const reason = value(formData, "reason"); const notes = value(formData, "notes"); const refundAmount = value(formData, "refund_amount") || "0"; const refundMethod = value(formData, "refund_method"); const refundReference = value(formData, "refund_reference"); const parsed = parseLines(value(formData, "lines"));
  if (!UUID.test(invoiceId)) return { ok: false, message: "This invoice is invalid.", field: "invoice_id" }; if (!returnNumber || returnNumber.length > 40 || !CODE.test(returnNumber)) return { ok: false, message: "Return number must use up to 40 letters, numbers, slashes, underscores, or hyphens.", field: "return_number" }; const dateError = validDate(returnDate, "Return date"); if (dateError) return { ok: false, message: dateError, field: "return_date" }; if (reason.length < 2 || reason.length > 200) return { ok: false, message: "Enter a return reason from 2 to 200 characters.", field: "reason" }; if (notes.length > 1000) return { ok: false, message: "Notes must be 1000 characters or fewer.", field: "notes" }; const refundError = decimal(refundAmount, "Refund amount", 2, true); if (refundError) return { ok: false, message: refundError, field: "refund_amount" }; const refundValue = Number(refundAmount); if (refundValue === 0 && refundMethod) return { ok: false, message: "Choose a refund method only when recording a refund.", field: "refund_method" }; if (refundValue > 0 && !refundMethod) return { ok: false, message: "Select a refund method.", field: "refund_method" }; if (refundReference.length > 100) return { ok: false, message: "Refund reference must be 100 characters or fewer.", field: "refund_reference" }; if (parsed.error || !parsed.lines) return { ok: false, message: parsed.error || "Select at least one item to return.", field: "lines" };
  const context = await getWorkspaceContext(); if (context.status !== "ready") return contextError(context.status); if (!(await permission(context, "returns.create"))) return { ok: false, message: "You do not have permission to create sales returns." };
  const { data, error } = await context.supabase.rpc("create_sales_return", { p_invoice_id: invoiceId, p_return_number: returnNumber, p_return_date: returnDate, p_reason: reason, p_notes: notes || null, p_refund_amount: refundAmount, p_refund_method: refundMethod || null, p_refund_reference: refundReference || null, p_lines: parsed.lines });
  if (error || !data) return processError(error || { message: "Missing return ID" }, "create");
  revalidatePath("/sales-returns"); revalidatePath(`/sales-returns/${data}`); revalidatePath(`/invoices/${invoiceId}`); return { ok: true, message: "Sales return saved as draft.", documentId: data };
}

async function processReturn(id: string, fn: "post_sales_return" | "cancel_sales_return", key: "returns.post" | "returns.create", action: "post" | "cancel") { if (!UUID.test(id)) return { ok: false, message: "This sales return ID is invalid." }; const context = await getWorkspaceContext(); if (context.status !== "ready") return contextError(context.status); if (!(await permission(context, key))) return { ok: false, message: `You do not have permission to ${action} sales returns.` }; const { error } = await context.supabase.rpc(fn, { p_return_id: id }); if (error) return processError(error, action); revalidatePath("/sales-returns"); revalidatePath(`/sales-returns/${id}`); revalidatePath("/invoices"); revalidatePath("/payments"); revalidatePath("/inventory"); revalidatePath("/stock-movements"); return { ok: true, message: action === "post" ? "Sales return posted and stock restocked." : "Sales return cancelled.", documentId: id }; }
export async function postSalesReturn(id: string): Promise<SalesReturnActionResult> { return processReturn(id, "post_sales_return", "returns.post", "post"); }
export async function cancelSalesReturn(id: string): Promise<SalesReturnActionResult> { return processReturn(id, "cancel_sales_return", "returns.create", "cancel"); }
